index:
    path: /
    controller: App\Controller\DefaultController::index

login:
  path: /login
  controller: App\Controller\UsersController::login

sign_in:
  path: /sign_in
  controller: App\Controller\UsersController::sign

log_out:
  path: /logout
  controller: App\Controller\UsersController::log_out
