<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCxGkqw9\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCxGkqw9/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCxGkqw9.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCxGkqw9\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCxGkqw9\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CxGkqw9',
    'container.build_id' => 'bc256a15',
    'container.build_time' => 1541598156,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCxGkqw9');
