<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJgULTjl\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJgULTjl/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJgULTjl.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJgULTjl\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJgULTjl\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JgULTjl',
    'container.build_id' => 'b979a720',
    'container.build_time' => 1542123818,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJgULTjl');
